name: satchip
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10
  - pip
  - gdal
  - numpy
  - shapely
  - pyproj
  - pystac-client
  - rasterio
  - zarr
  - xarray
  - rioxarray
  - pandas
  - geopandas
  - tqdm
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - pip:
      - -r requirements-static.txt
